version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    network_mode: "host"
    volumes:
      - .:/app/files